define nginx::location (
  Optional[Variant[String, Integer] $absolute_redirect = undef,
  Optional[Variant[String, Integer] $aio = undef,
  Optional[Variant[String, Integer] $aio_write = undef,
  Optional[Variant[String, Integer] $alias = undef,
  Optional[Variant[String, Integer] $chunked_transfer_encoding = undef,
  Optional[Variant[String, Integer] $client_body_buffer_size = undef,
  Optional[Variant[String, Integer] $client_body_in_file_only = undef,
  Optional[Variant[String, Integer] $client_body_in_single_buffer = undef,
  Optional[Variant[String, Integer] $client_body_temp_path = undef,
  Optional[Variant[String, Integer] $client_body_timeout = undef,
  Optional[Variant[String, Integer] $client_max_body_size = undef,
  Optional[Variant[String, Integer] $default_type = undef,
  Optional[Variant[String, Integer] $directio = undef,
  Optional[Variant[String, Integer] $directio_alignment = undef,
  Optional[Variant[String, Integer] $disable_symlinks = undef,
  Optional[Variant[String, Integer] $error_page = undef,
  Optional[Variant[String, Integer] $etag = undef,
  Optional[Variant[String, Integer] $if_modified_since = undef,
  Optional[Variant[String, Integer] $internal = undef,
  Optional[Variant[String, Integer] $keepalive_disable = undef,
  Optional[Variant[String, Integer] $keepalive_requests = undef,
  Optional[Variant[String, Integer] $keepalive_timeout = undef,
  Optional[Variant[String, Integer] $limit_except = undef,
  Optional[Variant[String, Integer] $limit_rate = undef,
  Optional[Variant[String, Integer] $limit_rate_after = undef,
  Optional[Variant[String, Integer] $lingering_close = undef,
  Optional[Variant[String, Integer] $lingering_time = undef,
  Optional[Variant[String, Integer] $lingering_timeout = undef,
  Optional[Variant[String, Integer] $location = undef,
  Optional[Variant[String, Integer] $log_not_found = undef,
  Optional[Variant[String, Integer] $log_subrequest = undef,
  Optional[Variant[String, Integer] $max_ranges = undef,
  Optional[Variant[String, Integer] $msie_padding = undef,
  Optional[Variant[String, Integer] $msie_refresh = undef,
  Optional[Variant[String, Integer] $open_file_cache = undef,
  Optional[Variant[String, Integer] $open_file_cache_errors = undef,
  Optional[Variant[String, Integer] $open_file_cache_min_uses = undef,
  Optional[Variant[String, Integer] $open_file_cache_valid = undef,
  Optional[Variant[String, Integer] $output_buffers = undef,
  Optional[Variant[String, Integer] $port_in_redirect = undef,
  Optional[Variant[String, Integer] $postpone_output = undef,
  Optional[Variant[String, Integer] $read_ahead = undef,
  Optional[Variant[String, Integer] $recursive_error_pages = undef,
  Optional[Variant[String, Integer] $reset_timedout_connection = undef,
  Optional[Variant[String, Integer] $resolver = undef,
  Optional[Variant[String, Integer] $resolver_timeout = undef,
  Optional[Variant[String, Integer] $root = undef,
  Optional[Variant[String, Integer] $satisfy = undef,
  Optional[Variant[String, Integer] $send_lowat = undef,
  Optional[Variant[String, Integer] $send_timeout = undef,
  Optional[Variant[String, Integer] $sendfile = undef,
  Optional[Variant[String, Integer] $sendfile_max_chunk = undef,
  Optional[Variant[String, Integer] $server_name_in_redirect = undef,
  Optional[Variant[String, Integer] $server_tokens = undef,
  Optional[Variant[String, Integer] $tcp_nodelay = undef,
  Optional[Variant[String, Integer] $tcp_nopush = undef,
  Optional[Variant[String, Integer] $try_files = undef,
  Optional[Variant[String, Integer] $types = undef,
  Optional[Variant[String, Integer] $types_hash_bucket_size = undef,
  Optional[Variant[String, Integer] $types_hash_max_size = undef,
) inherits nginx::config {

  concat { "/etc/nginx/servers.d/${name}.conf":
    ensure_newline => true,
  }

  concat::fragment{ "${name}_server_head":
    content => 'server {',
    target  => "/etc/nginx/servers.d/${name}.conf",
    order   => '00',
  }

  concat::fragment{ "${name}_server_conf":
    content => template('nginx/server/shared.erb'),
    target  => "/etc/nginx/servers.d/${name}.conf",
    order   => '01',
  }

  concat::fragment{ "${name}_server_bottom":
    content => '}',
    target  => "/etc/nginx/servers.d/${name}.conf",
    order   => '02',
  }
}

